### ISSUE TITLE
Crash on large number of powers

### ISSUE THREAD

**Issue by shuvashish76** [sadellie/unitto#12]
Crash logs:

```
fatal exception: main
process: com.sadellie.unitto, pid: 27077
java.lang.illegalargumentexception: can't represent a size of 721241 in constraints
 at pt$a.a(unknown source:54)
 at pt$a.b(unknown source:17)
 at y.a(unknown source:25)
 at y.c(unknown source:18)
 at mn2.a(sourcefile:373)
 at en2$b.d(sourcefile:29)
 at on0.f(sourcefile:39)
 at vd2.v(sourcefile:6)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at sa0.v(sourcefile:104)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at k11.c(sourcefile:9)
 at tf2$a.a(sourcefile:64)
 at sg2.c(sourcefile:7)
 at v0.c0(sourcefile:44)
 at ln1.a(sourcefile:75)
 at i11$b.m0(sourcefile:172)
 at i11$b.f(sourcefile:169)
 at o9.d(sourcefile:33)
 at on0.f(sourcefile:39)
 at xe.v(sourcefile:6)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at v80.v(sourcefile:6)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at a9.v(sourcefile:19)
 at a11.v(sourcefile:13)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at k11.c(sourcefile:9)
 at tf2$a.a(sourcefile:64)
 at sg2.c(sourcefile:7)
 at v0.c0(sourcefile:44)
 at ln1.a(sourcefile:75)
 at i11$b.m0(sourcefile:172)
 at i11$b.f(sourcefile:169)
 at i9.d(sourcefile:49)
 at on0.f(sourcefile:39)
 at l9$b.v(sourcefile:6)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at k11.c(sourcefile:9)
 at tf2$a.a(sourcefile:64)
 at sg2.c(sourcefile:7)
 at v0.c0(sourcefile:44)
 at ln1.a(sourcefile:75)
 at i11$b.m0(sourcefile:172)
 at i11$b.f(sourcefile:169)
 at q31.n0(sourcefile:60)
 at r51.a(unknown source:10)
 at y41.x(sourcefile:25)
 at m31.x(sourcefile:26)
 at m11.d(sourcefile:58)
 at on0.f(sourcefile:39)
 at vd2.v(sourcefile:6)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at x53.v(sourcefile:64)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at sa0.v(sourcefile:104)
 at yd.v(unknown source:14)
 at c11.f(sourcefile:11)
 at k11.c(sourcefile:9)
 at tf2$a.a(sourcefile:64)
 at sg2.c(sourcefile:7)
 at v0.c0(sourcefile:44)
 at ln1.a(sourcefile:75)
 at i11$b.m0(sourcefile:172)
 at f11.o(sourcefile:17)
 at ac1.c(sourcefile:25)
 at ac1.j(sourcefile:131)
 at ac1.f(sourcefile:69)
 at androidx.compose.ui.platform.androidcomposeview.c(sourcefile:14)
 at androidx.compose.ui.platform.androidcomposeview.dispatchdraw(sourcefile:22)
 at android.view.view.draw(view.java:19199)
 at android.view.view.updatedisplaylistifdirty(view.java:18146)
 at android.view.viewgroup.recreatechilddisplaylist(viewgroup.java:4220)
 at android.view.viewgroup.dispatchgetdisplaylist(viewgroup.java:4200)
 at android.view.view.updatedisplaylistifdirty(view.java:18105)
 at android.view.viewgroup.recreatechilddisplaylist(viewgroup.java:4220)
 at android.view.viewgroup.dispatchgetdisplaylist(viewgroup.java:4200)
 at android.view.view.updatedisplaylistifdirty(view.java:18105)
 at android.view.viewgroup.recreatechilddisplaylist(viewgroup.java:4220)
 at android.view.viewgroup.dispatchgetdisplaylist(viewgroup.java:4200)
 at android.view.view.updatedisplaylistifdirty(view.java:18105)
 at android.view.viewgroup.recreatechilddisplaylist(viewgroup.java:4220)
 at android.view.viewgroup.dispatchgetdisplaylist(viewgroup.java:4200)
 at android.view.view.updatedisplaylistifdirty(view.java:18105)
 at android.view.threadedrenderer.updateviewtreedisplaylist(threadedrenderer.java:676)
 at android.view.threadedrenderer.updaterootdisplaylist(threadedrenderer.java:682)
 at android.view.threadedrenderer.draw(threadedrenderer.java:790)
 at android.view.viewrootimpl.draw(viewrootimpl.java:3006)
 at android.view.viewrootimpl.performdraw(viewrootimpl.java:2810)
 at android.view.viewrootimpl.performtraversals(viewrootimpl.java:2363)
 at android.view.viewrootimpl.dotraversal(viewrootimpl.java:1396)
 at android.view.viewrootimpl$traversalrunnable.run(viewrootimpl.java:6773)
 at android.view.choreographer$callbackrecord.run(choreographer.java:966)
at android.view.choreographer.docallbacks(choreographer.java:778)
 at android.view.choreographer.doframe(choreographer.java:713)
 at android.view.choreographer$framedisplayeventreceiver.run(choreographer.java:952)
 at android.os.handler.handlecallback(handler.java:790)
 at android.os.handler.dispatchmessage(handler.java:99)
 at android.os.looper.loop(looper.java:164)
 at android.app.activitythread.main(activitythread.java:6518)
 at java.lang.reflect.method.invoke(native method)
 at com.android.internal.os.runtimeinit$methodandargscaller.run(runtimeinit.java:438)
 at com.android.internal.os.zygoteinit.main(zygoteinit.java:807)
```

Steps to reproduce: e.g. 111^1111,  99^9999, 9^8765 etc...

**Comment by sadellie** [comment]
No more crashes, BUT a little bug was added.
1. Enter `99^9999999` (very BIG)
2. Clear input and enter `2+2` before previous conversion completes

Previous conversion is not canceled and conversion for `2+2` doesn't show up.
Workaround: click "swap units" button. Now conversion for `2+2` shows up.

It's highly unlikely that user will enter `99^9999999`, so I will leave this bug as is and come back to it if I find a solution.

_Crash is fixed, so I'm closing this issue. Thank you for reporting it._
